### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by uygarpolat** [930913/framework32#3] opened 2021-02-24 01:19 UTC
Hi, as of today, only the bitcoin tracker app retrieves results for me. Lichess gives "Connecting to stream de: 404" and "Got disconnected" error. Octoprint gives -1 status code (this may be my issue?), and BBC app just crashes. I would have concluded that it's an issue on my end but the Bitcoin tracker is working well. Cheers!

**Comment by 930913** [comment] 2021-02-24 13:22
Thanks for reporting this. I am also seeing the same errors for Lichess, so I presume they've changed their API and broken compatibility. I'll have to investigate and fix.

Octoprint giving -1 suggests that it can't find your Octoprint server. Double check you have set the config correctly, and ensure that the Octoprint API is accessible.

BBC just crashing is strange. I can't reproduce that on mine. Could you add the serial output (115200 baud) here to give me some idea of what might be happening?

**Comment by uygarpolat** [comment] 2021-02-24 14:31
I couldn't replicate the BBC issue, it works fine right now. I'll post the output if it arises again. One minor thing is, whenever I return to home from BBC app, the upper section where the time, wifi, battery symbols are, it flickers for a couple of seconds (not the entire screen). If I try to enter another app during the flicker, it doesn't connect. Here's what I get after double left clicking to exit the BBC app.

```
Button 2 pressed double.
assertion "heap != NULL && "free() target pointer is outside heap areas"" failed: file "/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/componenBts/heap/heap_caps.c", line 267, function: heap_caps_free
abort() was called at PC 0x401302e3 on core 0

Backtrace: 0x4008de60:0x3ffd3d90 0x4008e091:0x3ffd3db0 0x401302e3:0x3ffd3dd0 0x40085017:0x3ffd3e00 0x40086929:0x3ffd3e20 0x4000bec7:0x3ffd3e40 0x40162ce1:0x3ffd3e60 0x400d21d5:0x3ffd3e80 0x400d36f1:0x3ffd3ea0 0x400e0b22:0x3ffd3ec0 0x400d3940:0x3ffd3ee0 0x400d7ce2:0x3ffd3f00 0x4008a5a9:0x3ffd4020

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
Start
Loading config
Config loaded
eFuse Vref:1086 mVInitialising buttons
```


For Octoprint, I double checked server and application key and they look right but I still get -1. Could it be because my octoprint address uses http rather than https? Here's what I get from serial:

```
[HTTPS] begin...
[HTTPS] GET...
[HTTPS] GET... failed, error: connection refused
[HTTPS] failed with status code: -1
```

I'm really looking forward to the Lichess functionality returning, bought LiPo batteries just for that! Thanks for the framework, I hope it takes off!

**Comment by 930913** [comment] 2021-02-24 21:55
Lichess changed one of their URLs, so that's been fixed with #4.

Octoprint is expecting HTTPS - though you don't need to worry about a self-signed certificate, as it's not validating them from a CA.

I noticed the BBC app has been crashing on close for me too, but I haven't gone and looked why that is yet, probably because the crash behaviour is so similar to the expected close behaviour :smile:

**Comment by 930913** [comment] 2021-02-24 22:06
BBC shouldn't crash now.

**Comment by uygarpolat** [comment] 2021-02-25 00:16
Perfect, all of the issues are solved, including Octoprint. Here are some more ideas before you close this thread:

1) Being able to access different cryptocurrencies.
2) A weather app.
3) A flashcard app, to memorize stuff, like vocabulary in another language.

**Comment by 930913** [comment] 2021-02-25 22:02
1. Nice idea, I suspect it might not be too hard with the coinbase API.
2. I looked into this, I couldn't find an API of weather that doesn't require an API key. When you see other people demo, they've used their own API key that they've got, but I don't particularly like the idea of making an app where you have to sign up to a third party to get a key. If you do know of a service, please let me know!
3. Has potential, but configuring it will be awkward, and any non ASCII font probably won't render.

(Closing as resolved, but comments can still be added.)

**Closed as completed by 930913** 2021-02-25 22:02 UTC
